apiVersion: v1
kind: Service
metadata:
  name: simple-echo-api-service
  namespace: playground
spec:
  selector:
    app: simple-echo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
