# https://taskfile.dev

version: "3"

env:
  APP_NAME: echo-api

tasks:
  build:
    cmds:
      - go build ./src/server.go

  start-server:
    cmds:
      - ./server

  start-dev-server:
    cmds:
      - go run ./src/server.go

  build-image:
    cmds:
      - docker build -t $APP_NAME -f docker/dockerfile .

  deploy:
    cmds:
      - docker run -d -p 80:8080 --name  $APP_NAME $APP_NAME

  stop-container:
    cmds:
      - docker stop  $APP_NAME

  remove-container:
    cmds:
      - docker rm $APP_NAME

  test-app:
    deps:
      - deploy
    cmds:
      - curl  -H 'app:Hello world' http://localhost
