# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build ./src/server.go

  start-server:
    cmds:
      - ./server

  start-dev-server:
    cmds:
      - go run ./src/server.go
