name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go
        run: go  version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install Taskfile tool
        uses: arduino/setup-task@v1

      - name: build/compile application
        run: task build

      - name: build docker image
        run: task build-image

      - name: Invoke/test app
        run: task test-app
